### ISSUE TITLE
Running on OSX gives jcuda.CudaException: CUDA_ERROR_OPERATING_SYSTEM

### ISSUE THREAD

**Issue by nlothian** [IBMSparkGPU/GPUEnabler#25]
Hi,

I'm trying to test this out on a MacBook under OSX.

NVidia deviceQuery gives the following:

```
 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 750M"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.0
```

With the default resources/Makefile I get the following error:

```
./bin/run-example GpuEnablerExample
Executing : mvn -q scala:run -DmainClass=com.ibm.gpuenabler.GpuEnablerExample -DaddArgs="local[*]"
16/08/09 16:37:12 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
jcuda.CudaException: CUDA_ERROR_NO_BINARY_FOR_GPU
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326)
	at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2028)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:96)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:80)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:80)
	at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)
	at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:108)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
```

Changing the makefile  to
```
#COMPUTE_CAPABILITY ?= 30
COMPUTE_CAPABILITY ?= 30
```

Now I get
```
Executing : mvn -q scala:run -DmainClass=com.ibm.gpuenabler.GpuEnablerExample -DaddArgs="local[*]"
16/08/09 16:39:07 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
jcuda.CudaException: CUDA_ERROR_OPERATING_SYSTEM
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326)
	at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2028)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:96)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:80)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:80)
	at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)
	at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:108)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
```

I'm not too sure what to try with this error. The only thing I can find about it is https://forum.byte-welt.net/archive/index.php/t-3068.html, which seems to have been back in the CUDA 3.1 days, (I have CUDA 7.5 installed).

I can run eg TensorFlow/Theano successfully.

Any hints would be appreciated.

**Comment by kmadhugit** [comment]
Hi Nick,

Can you try simple JCUDA sample
http://www.jcuda.org/tutorial/TutorialIndex.html#BasicTest to rule out
setup issues? Then try to export jcuda driver files(*.dylib) through
LD_LIBRARY_PATH and run GPUEnabler?

Thanks,
Madhu.
_________________________________
Madhusudanan Kandasamy
IBM Master Inventor
TCEM - AIX Performance, Scalability and DSO.
Bangalore.

**Comment by nlothian** [comment]
I ran the JCUDA sample successfully:

```
JCuda-All-0.7.5-bin-apple-x86_64 java -cp ".:jcuda-0.7.5.jar" JCudaRuntimeTest
Pointer: Pointer[nativePointer=0x200a80000,byteOffset=0]
```

I tried setting LD_LIBRARY_PATH to the JCuda dylib files, but GpuEnablerExample worked exactly the same. I also tried setting DYLD_LIBRARY_PATH (which is how the CUDA library path seems to be set) and it didn't help either. 

I think that if it was an error in my CUDA setup then changing COMPUTE_CAPABILITY wouldn't make any difference? For me it does change the error message, which I think indicates that my CUDA setup is ok? I'm not really sure about this though.

**Comment by YuxinxinChen** [comment]
I also met the same problem, @nlothian did you solve the problem and how?

**Comment by nlothian** [comment]
@YuxinxinChen no I didn't.
