### ISSUE TITLE
Maven executes tests for gpu-enabler before native libs are deployed

### ISSUE THREAD

**Issue by TPolzer** [IBMSparkGPU/GPUEnabler#26]
Trying to build the whole thing from a clean checkout fails:
```
$ mvn 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] gpu-enabler-parent
[INFO] mavenized-jcuda
[INFO] gpu-enabler_2.10
[INFO] GPU Enabler Examples
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gpu-enabler-parent 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mavenized-jcuda 0.1.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mavenized-jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home.stand/inf2/****/GPUEnabler/mavenized-jcuda/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ mavenized-jcuda ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home.stand/inf2/****/GPUEnabler/mavenized-jcuda/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mavenized-jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home.stand/inf2/****/GPUEnabler/mavenized-jcuda/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ mavenized-jcuda ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mavenized-jcuda ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ mavenized-jcuda ---
[INFO] Building jar: /home.stand/inf2/****/GPUEnabler/mavenized-jcuda/target/mavenized-jcuda-0.1.2.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gpu-enabler_2.10 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (eclipse-add-source) @ gpu-enabler_2.10 ---
[INFO] Add Test Source directory: /home.stand/inf2/****/GPUEnabler/gpu-enabler/src/scala
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gpu-enabler_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home.stand/inf2/****/GPUEnabler/gpu-enabler/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ gpu-enabler_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 9 Scala sources to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/scala-2.10/classes...
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ gpu-enabler_2.10 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] >>> scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) > generate-sources @ gpu-enabler_2.10 >>>
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (eclipse-add-source) @ gpu-enabler_2.10 ---
[INFO] 
[INFO] <<< scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) < generate-sources @ gpu-enabler_2.10 <<<
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) @ gpu-enabler_2.10 ---
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=64m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
model contains 17 documentable templates
[INFO] Building jar: /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/gpu-enabler_2.10-1.0.0-javadoc.jar
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ gpu-enabler_2.10 ---
[INFO] Checking for multiple versions of scala
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] /home.stand/inf2/****/GPUEnabler/gpu-enabler/src/main/scala:-1: info: compiling
[INFO] Compiling 9 source files to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/scala-2.10/classes at 1472544620992
[INFO] prepare-compile in 0 s
[INFO] compile in 8 s
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gpu-enabler_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (scala-test-compile-first) @ gpu-enabler_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 1 Scala source and 1 Java source to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/scala-2.10/test-classes...
[WARNING] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[WARNING] 1 warning
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ gpu-enabler_2.10 ---
[INFO] Compiling 1 source file to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/scala-2.10/test-classes
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:build-classpath (default) @ gpu-enabler_2.10 ---
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:testCompile (default) @ gpu-enabler_2.10 ---
[INFO] Checking for multiple versions of scala
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] /home.stand/inf2/****/GPUEnabler/gpu-enabler/src/test:-1: info: compiling
[INFO] Compiling 2 source files to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/scala-2.10/test-classes at 1472544639201
[INFO] prepare-compile in 0 s
[INFO] compile in 7 s
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ gpu-enabler_2.10 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.ibm.gpuenabler.TestJavaCUDASuite
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.291 sec <<< FAILURE! - in com.ibm.gpuenabler.TestJavaCUDASuite
MultiMultiSum(com.ibm.gpuenabler.TestJavaCUDASuite)  Time elapsed: 1.941 sec  <<< ERROR!
org.apache.spark.SparkException: Could not initialize CUDA, because native jCuda libraries were not detected - make sure Driver and Executors are able to load them
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiMultiSum(TestJavaCUDASuite.java:169)
Caused by: java.lang.UnsatisfiedLinkError: 
Could not load the native library.
Error while loading native library "JCudaDriver-linux-x86_64" with base name "JCudaDriver"
Operating system name: Linux
Architecture         : amd64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJCudaDriver-linux-x86_64.so'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:255)
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv.<init>(GPUSparkEnv.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv$.initalize(GPUSparkEnv.scala:58)
	at com.ibm.gpuenabler.GPUSparkEnv$.get(GPUSparkEnv.scala:66)
	at com.ibm.gpuenabler.CUDAFunction.<init>(CUDAFunction.scala:219)
	at com.ibm.gpuenabler.JavaCUDAFunction.<init>(CUDAFunction.scala:132)
	at com.ibm.gpuenabler.JavaCUDAFunction.<init>(CUDAFunction.scala:141)
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiMultiSum(TestJavaCUDASuite.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaDriver-linux-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:255)
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv.<init>(GPUSparkEnv.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv$.initalize(GPUSparkEnv.scala:58)
	at com.ibm.gpuenabler.GPUSparkEnv$.get(GPUSparkEnv.scala:66)
	at com.ibm.gpuenabler.CUDAFunction.<init>(CUDAFunction.scala:219)
	at com.ibm.gpuenabler.JavaCUDAFunction.<init>(CUDAFunction.scala:132)
	at com.ibm.gpuenabler.JavaCUDAFunction.<init>(CUDAFunction.scala:141)
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiMultiSum(TestJavaCUDASuite.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiMultiSum(TestJavaCUDASuite.java:169)

MultiSum(com.ibm.gpuenabler.TestJavaCUDASuite)  Time elapsed: 0.18 sec  <<< ERROR!
org.apache.spark.SparkException: Could not initialize CUDA, because native jCuda libraries were not detected - make sure Driver and Executors are able to load them
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiSum(TestJavaCUDASuite.java:106)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jcuda.driver.JCudaDriver
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiSum(TestJavaCUDASuite.java:106)

MultiPart(com.ibm.gpuenabler.TestJavaCUDASuite)  Time elapsed: 0.156 sec  <<< ERROR!
org.apache.spark.SparkException: Could not initialize CUDA, because native jCuda libraries were not detected - make sure Driver and Executors are able to load them
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiPart(TestJavaCUDASuite.java:75)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jcuda.driver.JCudaDriver
	at com.ibm.gpuenabler.TestJavaCUDASuite.MultiPart(TestJavaCUDASuite.java:75)


Results :

Tests in error: 
  TestJavaCUDASuite.MultiMultiSum:169 » Spark Could not initialize CUDA, because...
  TestJavaCUDASuite.MultiPart:75 » Spark Could not initialize CUDA, because nati...
  TestJavaCUDASuite.MultiSum:106 » Spark Could not initialize CUDA, because nati...

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gpu-enabler-parent ................................. SUCCESS [  0.002 s]
[INFO] mavenized-jcuda .................................... SUCCESS [  1.433 s]
[INFO] gpu-enabler_2.10 ................................... FAILURE [ 46.458 s]
[INFO] GPU Enabler Examples ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.984 s
[INFO] Finished at: 2016-08-30T08:10:50+00:00
[INFO] Final Memory: 69M/1071M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project gpu-enabler_2.10: There are test failures.
[ERROR] 
[ERROR] Please refer to /home.stand/inf2/****/GPUEnabler/gpu-enabler/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gpu-enabler_2.10
```

Doing `mvn package -DskipTests && mvn package` works. It seems that the native libraries in gpu-enabler/target/lib are only put there after the tests.

**Comment by josiahsams** [comment]
Yes. Its absolutely necessary to run "mvn package -DskipTests" before running the tests (mvn test) as the CUDA native libraries are made part of the .jar by "copy-dependencies" goal during the "package" mvn phase.
