### ISSUE TITLE
error while executing gpuenabler example 

### ISSUE THREAD

**Issue by tijoparacka** [IBMSparkGPU/GPUEnabler#31]
Hi I am getting this error when i tried to execute in   g2.2xlarge instance in aws. I used Openjdk and scala 11.8  . I installed cuda driver from nvida site. 

affter ./compile.sh 
I executed ./bin/run-example GpuEnablerExample 

ubuntu@ip-172-31-11-228:~/GPUEnabler$ ./bin/run-example GpuEnablerExample
```
Executing : mvn -q scala:run -DmainClass=com.ibm.gpuenabler.GpuEnablerExample -DaddArgs="local[*]"
modprobe: ERROR: could not insert 'nvidia_361_uvm': Unknown symbol in module, or unknown parameter (see dmesg)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: org.apache.spark.SparkException: Could not initialize CUDA because of unknown reason
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:53)
	at com.ibm.gpuenabler.GPUSparkEnv.<init>(GPUSparkEnv.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv$.initalize(GPUSparkEnv.scala:58)
	at com.ibm.gpuenabler.GPUSparkEnv$.get(GPUSparkEnv.scala:66)
	at com.ibm.gpuenabler.CUDAFunction.<init>(CUDAFunction.scala:219)
	at com.ibm.gpuenabler.GpuEnablerExample$.main(GpuEnablerExample.scala:31)
	at com.ibm.gpuenabler.GpuEnablerExample.main(GpuEnablerExample.scala)
	... 6 more
Caused by: jcuda.CudaException: CUDA_ERROR_UNKNOWN
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:312)
	at jcuda.driver.JCudaDriver.cuInit(JCudaDriver.java:439)
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:43)
	... 12 more
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:run (default-cli) on project gpu-enabler-examples_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240) -> [Help 1
```

**Comment by kavanabhat** [comment]
CUDA initialization has failed. Please check if the solution detailed in the below site helps:
https://github.com/fchollet/keras/issues/3043
