### ISSUE TITLE
jcuda  seems error

### ISSUE THREAD

**Issue by xuxilei** [IBMSparkGPU/GPUEnabler#33]
when execute, jcuda  seems error:
16/12/21 06:38:25 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)

jcuda.CudaException: CUDA_ERROR_NO_BINARY_FOR_GPU

         at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:312)

         at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2014)

         at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:96)

         at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:80)

         at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)

         at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)

         at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:80)

         at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)

         at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:108)

         at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)

**Comment by xuxilei** [comment]
i know the .ptx is not ready

**Comment by YuxinxinChen** [comment]
Hi, @xuxilei  I have the same problem, How did you solve the problem? What do you mean the .ptx is not ready?

**Comment by ShengjieLuo** [comment]
Hi, @xuxilei @YuxinxinChen I have the same problem, could you tell me the method that you solve the problem?
