### ISSUE TITLE
Executing example with master=yarn

### ISSUE THREAD

**Issue by dimon777** [IBMSparkGPU/GPUEnabler#40]
I am trying to submit an example from edge node which doesn't have GPU against yarn cluster with datanodes having GPUS like this:
spark-submit --master=yarn --jars gpu-enabler/target/gpu-enabler_2.11-1.0.0.jar --class com.ibm.gpuenabler.GpuEnablerCodegen examples/target/gpu-enabler-examples_2.11-1.0.0.jar

I am getting this error:

```
Caused by: org.apache.spark.SparkException: Could not initialize CUDA because of unknown reason
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:53)
	at com.ibm.gpuenabler.GPUSparkEnv.<init>(GPUSparkEnv.scala:42)
	at com.ibm.gpuenabler.GPUSparkEnv$.initalize(GPUSparkEnv.scala:58)
	at com.ibm.gpuenabler.GPUSparkEnv$.get(GPUSparkEnv.scala:66)
	at com.ibm.gpuenabler.CUDACodeGenerator$.<init>(CUDACodeGenerator.scala:207)
	at com.ibm.gpuenabler.CUDACodeGenerator$.<clinit>(CUDACodeGenerator.scala)
	... 12 more
Caused by: jcuda.CudaException: CUDA_ERROR_NO_DEVICE
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:312)
	at jcuda.driver.JCudaDriver.cuInit(JCudaDriver.java:439)
	at com.ibm.gpuenabler.CUDAManager.<init>(CUDAManager.scala:43)
```

I understand the error is because there no GPU on the edge node. so my questions are:

1. Does this GPUEnabler support submitting jobs against yarn to run on GPU enabled cluster nodes? Or it only supports submission against one local node with GPU?
2. What should be the workflow to submit jobs in my configuration: edge node w.o GPU and cluster nodes with GPUs?
3. What jCuda library I have to use in Spark (I see many after successful build of GPUEnabler):
```

./mavenized-jcuda/repo/jcuda/jcuda/0.6.0/jcuda-0.6.0.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.6.0RC/jcuda-0.6.0RC.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.7.5/jcuda-0.7.5.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.7.0a/jcuda-0.7.0a.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.5.5/jcuda-0.5.5.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.6.5/jcuda-0.6.5.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.7.5b/jcuda-0.7.5b.jar
./mavenized-jcuda/repo/jcuda/jcuda/0.5.0/jcuda-0.5.0.jar
./mavenized-jcuda/target/mavenized-jcuda-0.1.2.jar
```
Thanks!

**Comment by IslandGod** [comment]
About your problems:
Does GPUEnabler support submitting jobs with MASTER=yarn to run on GPU enabled cluster nodes? Or it only supports submission against one local node with GPU?
What should be the workflow to submit jobs in my configuration: edge node w.o GPU and cluster nodes with GPUs?

I'm having the same issue , did you find any answer? 
thanks

**Comment by dimon777** [comment]
I couldn not find solution for this. At some point gpu support will be implemented in spark anyway.

Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: IslandGod <notifications@github.com> Date: 4/5/17  4:12 AM  (GMT-05:00) To: IBMSparkGPU/GPUEnabler <GPUEnabler@noreply.github.com> Cc: dimon777 <dbouzolin@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [IBMSparkGPU/GPUEnabler] Executing example with master=yarn gives
  CUDA_ERROR_NO_DEVICE error (#40) 
About your problems:

Does GPUEnabler support submitting jobs with MASTER=yarn to run on GPU enabled cluster nodes? Or it only supports submission against one local node with GPU?

What should be the workflow to submit jobs in my configuration: edge node w.o GPU and cluster nodes with GPUs?
I'm having the same issue , did you find any answer?

thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IBMSparkGPU/GPUEnabler","title":"IBMSparkGPU/GPUEnabler","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/IBMSparkGPU/GPUEnabler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@IslandGod in #40: About your problems:\r\nDoes GPUEnabler support submitting jobs with MASTER=yarn to run on GPU enabled cluster nodes? Or it only supports submission against one local node with GPU?\r\nWhat should be the workflow to submit jobs in my configuration: edge node w.o GPU and cluster nodes with GPUs?\r\n\r\nI'm having the same issue , did you find any answer? \r\nthanks\r\n"}],"action":{"name":"View Issue","url":"https://github.com/IBMSparkGPU/GPUEnabler/issues/40#issuecomment-291787193"}}}

**Comment by IslandGod** [comment]
Whatever I use `./sbin/start-all.sh` to active my clusters or not,  I can use the same cmd like: 
`spark-submit --master=spark://10.1.12.201:7077 --jars gpu-enabler/target/gpu-enabler_2.11-1.0.0.jar --class com.ibm.gpuenabler.GpuEnablerCodegen examples/target/gpu-enabler-examples_2.11-1.0.0.jar`
to get the some correct answer. 

So I wonder, does GPUEnabler really submit to clusters, or it just run locally?

all info will help, thanks

**Comment by kiszk** [comment]
It should work with local or standalone-cluster. However, we have not tested with yarn.

**Comment by dimon777** [comment]
"Whatever I use ./sbin/start-all.sh to active my clusters or not, I can use the same cmd like:"
start-all.sh simply starts hdfs and yarn stack in Hadoop, and Spark is decoupled from them. You can start standalone cluster and observe GPU status via nvidia-smi tool to judge if they use multi node GPUs or not. This can be evident from GPU memory consumption and temperature values.
