### ISSUE TITLE
Build & Runtime failure with Spark 2.2.0

### ISSUE THREAD

**Issue by josiahsams** [IBMSparkGPU/GPUEnabler#65]
GPUEnabler plugin fails on Spark 2.2.0 with the following error,

```
joe@soe15:~$ time ~/spark-2.2.0-bin-hadoop2.7/bin/spark-submit --master local[*] --conf spark.driver.memory=15g --class com.ibm.gpuenabler.perfDebugMod  --jars ~/new/GPUEnabler/gpu-enabler/target/gpu-enabler_2.11-1.0.0.jar ~/new/GPUEnabler/examples/target/gpu-enabler-examples_2.11-1.0.0.jar  | tee out
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.rpc.RpcEndpointRef.askWithRetry(Ljava/lang/Object;Lscala/reflect/ClassTag;)Ljava/lang/Object;
	at com.ibm.gpuenabler.GPUMemoryManager.tell(GPUMemoryManager.scala:301)
	at com.ibm.gpuenabler.GPUMemoryManager.<init>(GPUMemoryManager.scala:271)
	at com.ibm.gpuenabler.GPUSparkEnv.<init>(GPUSparkEnv.scala:47)
	at com.ibm.gpuenabler.GPUSparkEnv$.initalize(GPUSparkEnv.scala:76)
	at com.ibm.gpuenabler.GPUSparkEnv$.get(GPUSparkEnv.scala:88)
	at com.ibm.gpuenabler.CUDADSImplicits$CUDADSFuncs.cacheGpu(CUDADSUtils.scala:416)
	at com.ibm.gpuenabler.perfDebugMod$.main(perfDebugMod.scala:96)
	at com.ibm.gpuenabler.perfDebugMod.main(perfDebugMod.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

A fresh build too fails.

**Comment by josiahsams** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check this version for Spark 2.2.1 - BUG during complication w.r.t RPC](https://trello.com/c/YWMGgLsv/8-check-this-version-for-spark-221-bug-during-complication-wrt-rpc)

**Comment by imvs** [comment]
Something wrong with your dependencies https://github.com/apache/spark/commit/ba8912e5f3d5c5a366cb3d1f6be91f2471d048d2
