### ISSUE TITLE
CUDA_ERROR_INVALID_PTX on ./bin/run-example GpuEnablerExample

### ISSUE THREAD

**Issue by amansinha-sw** [IBMSparkGPU/GPUEnabler#77]
I have been trying to run the examples on my machine but it is failing with the below error:
(py35) aman@Aman:~/GPUEnabler$ ./bin/run-example GpuEnablerExample
Executing : mvn -q scala:run -DmainClass=com.ibm.gpuenabler.GpuEnablerExample -DaddArgs=""
/home/aman/GPUEnabler/examples
18/02/16 18:47:02 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
jcuda.CudaException: CUDA_ERROR_INVALID_PTX
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326)
	at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2028)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:103)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:88)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:88)
	at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)
	at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:109)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/02/16 18:47:02 ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): jcuda.CudaException: CUDA_ERROR_INVALID_PTX
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326)
	at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2028)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:103)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:88)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:88)
	at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)
	at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:109)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at com.ibm.gpuenabler.CUDARDDImplicits$CUDARDDFuncs.reduceExtFunc(CUDARDDUtils.scala:366)
	at com.ibm.gpuenabler.GpuEnablerExample$.main(GpuEnablerExample.scala:53)
	at com.ibm.gpuenabler.GpuEnablerExample.main(GpuEnablerExample.scala)
	... 6 more
Caused by: jcuda.CudaException: CUDA_ERROR_INVALID_PTX
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326)
	at jcuda.driver.JCudaDriver.cuModuleLoadData(JCudaDriver.java:2028)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:103)
	at com.ibm.gpuenabler.CUDAManager$$anonfun$cachedLoadModule$1.apply(CUDAManager.scala:88)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:88)
	at com.ibm.gpuenabler.CUDAFunction.compute(CUDAFunction.scala:334)
	at com.ibm.gpuenabler.MapGPUPartitionsRDD.compute(CUDARDDUtils.scala:109)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:run (default-cli) on project gpu-enabler-examples_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Please help me resolve the error.

**Comment by josiahsams** [comment]
Make sure you are running this program in machine with GPUs with capability >= 35. Else recompile the *.cu files under examples/src/main/resources/ directory by changing the Makefile with the correct "COMPUTE_CAPABILITY" inside it.

**Comment by amansinha-sw** [comment]
@josiahsams Thanks a lot, I had not checked that earlier. It worked now.
