### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wangwenGreentea** [IBMSparkGPU/GPUEnabler#89]
I  test your examples:GpuDSArrayMult,but get errors.

Caused by: java.lang.NullPointerException
        at com.ibm.gpuenabler.CUDAManager.cachedLoadModule(CUDAManager.scala:72)
        at com.ibm.gpuenabler.CUDAManager.getModule(CUDAManager.scala:62)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$JCUDAIteratorImpl.processGPU(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$JCUDAIteratorImpl.hasNext(Unknown Source)
        at com.ibm.gpuenabler.MAPGPUExec$$anonfun$doExecute$1.apply(CUDADSUtils.scala:152)
        at com.ibm.gpuenabler.MAPGPUExec$$anonfun$doExecute$1.apply(CUDADSUtils.scala:73)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)

**Comment by asdfghjBennyHuang** [comment]
It's actually same as my issue #86  . Indeed need some help on this.

If you just want to make it run, you can probably try disabling the spark.gpuenabler.autocache, I can eliminate the error and sort of resolve the issue, but we probably need to fix the issue properly?

**Comment by wangwenGreentea** [comment]
> It's actually same as my issue #86 . Indeed need some help on this.
> 
> If you just want to make it run, you can probably try disabling the spark.gpuenabler.autocache, I can eliminate the error and sort of resolve the issue, but we probably need to fix the issue properly?

**Comment by wangwenGreentea** [comment]
> > It's actually same as my issue #86 . Indeed need some help on this.
> > If you just want to make it run, you can probably try disabling the spark.gpuenabler.autocache, I can eliminate the error and sort of resolve the issue, but we probably need to fix the issue properly?

Thankyou! Even  I run it as local[*] , the same error still occurs.How to disable spark.gpuenabler.autocache

**Comment by asdfghjBennyHuang** [comment]
You can add a line in your $SPARK_HOME/conf/spark-defaults.conf. You can also refer to https://spark.apache.org/docs/latest/configuration.html
